### ISSUE TITLE
crush on attempt to call `__tls_get_addr`

### ISSUE THREAD

**Issue by magras** [Dead2/stabilizer#14]
I have no MRE, but `example` binary from zlib-ng crushes because of that.

It turns out in some cases access to a TLS variable can generate an IP relative call on the backend, which of course breaks if the function was relocated at runtime. Since it happens on the compiler backend I don't know how to distinguish cases when stabilizer should keep access to a TLS variable intact and when to replace it.

As always we can replace all accesses to TLS variables with a call to a non-relocatable helper function.

**Comment by Dead2** [comment]
Would perhaps the clang parameter `-femulated-tls` alleviate this problem?

I am unable to test/reproduce this, or rather on my system `example` crashes regardless of whether `Z_TLS` is enabled during compile or not.

**Comment by magras** [comment]
I think I found MRE:

```
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: Makefile
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ tls: main.cpp libtls.so
   2   │     ${CXX} -L. -ltls -o tls main.cpp
   3   │ libtls.so: libtls.cpp
   4   │     ${CXX} -shared -fPIC -o libtls.so libtls.cpp
───────┴─────────────────────────────────────────────────────────────────────────
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: libtls.cpp
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ thread_local int i;
   2   │ void foo() { ++i; }
───────┴─────────────────────────────────────────────────────────────────────────
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: main.cpp
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ void foo();
   2   │ int main() { foo(); }
───────┴─────────────────────────────────────────────────────────────────────────

$ SZ_CODE=1 SZ_LOWER=1 CXX=szcc++ make
```

@Dead2, thank you. `-femulated-tls` was a good find. At least it helped to minimize the example.

I'll need more time to try to find a solution because it seems that this transformation is applied by linker.

**Comment by magras** [comment]
I don't like the overhead of function wrappers, but I didn't find any other acceptable solutions.

In case of TLS it can be even more pronounced because I believe TLS is often used in performance critical path.

I was hoping I could at least merge consecutive calls, but atm simple `++i` translated to
```
call qword [sym.stabilizer.dummy._Z3foov]
mov ebx, dword [rax]
add ebx, 1
call qword [sym.stabilizer.dummy._Z3foov]
mov dword [rax], ebx
```

I'll make a new issue about this, because it is about relocation table used for all IP relative stuff, not TLS specifically.
