### ISSUE TITLE
szcc doesn't work from /usr/bin

### ISSUE THREAD

**Issue by magras** [Dead2/stabilizer#8]
I don't think that it is a good idea to check existence of `clang` at the same path. It makes impossible to install `szcc` to a system dir.

https://github.com/Dead2/stabilizer/blob/115c2f78288df717411e1fff641d1d5fb8edcdfb/szcc#L36-L37

**Comment by mtl1979** [comment]
I agree... Even though Linux kinda expects third-party binaries to be installed or symlinked in `/usr/local/bin` to avoid replacing binaries installed by package manager, this did make impossible building stabilizer itself as a package.

**Comment by magras** [comment]
Fixed in #30.
